### ISSUE TITLE
Codesign on macOS is broken when using PyQt5.Qml

### ISSUE THREAD

**Issue by BoboTiG** [pyinstaller/pyinstaller#3680]
Trying to codesign an application on macOS when PyQt5 QML is not possible.

Minimal real reproductible example is following but I could reduce the test case to something really small.

test.spec:
```python
# -*- mode: python -*-

a = Analysis(['test.py'],
             hiddenimports=["PyQt5.QtQuick"])
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='test',
          debug=False,
          strip=False,
          upx=False,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='test')
app = BUNDLE(
    coll,
    name="test.app",
)
```

test.py:
```python
import sys
sys.exit(0)
```

---

Real example, I do not know if it is helpfull, but still.

test.py (adapt the QML file path):
```python
# coding: utf-8
import sys
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QGuiApplication
from PyQt5.QtQml import QQmlApplicationEngine


def run():
    app = QGuiApplication([])

    engine = QQmlApplicationEngine(parent=app)
    engine.load(QUrl.fromLocalFile("~/test.qml"))

    if not engine.rootObjects():
        return -1

    return app.exec_()


sys.exit(run())
```

test.qml:
```css
import QtQuick 2.10
import QtQuick.Controls 2.3
import QtQuick.Layouts 1.3
import QtQuick.Dialogs 1.3

ApplicationWindow {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")

    FileDialog {
        id: fileDialog
        selectFolder: true

        onAccepted: {
            console.log('activated')
        }
    }

    Button {
        anchors.centerIn: parent
        text: "Open"
        onClicked: {
            fileDialog.open()
        }
    }
}
```

---

And finally, to check the code signing, test.sh (just set the evar `SIGNING_ID`):
```bash
#!/bin/bash

pkg_path="dist/test.app"

echo ">>> [sign] Signing the app"
codesign --deep --force -vs "${SIGNING_ID}" "${pkg_path}"
# find "${pkg_path}/Contents/MacOS" -type f -exec codesign -ds "${SIGNING_ID}" {} \;
# codesign -vs "${SIGNING_ID}" "${pkg_path}"

echo ">>> [sign] Verifying code signature"
codesign -vv "${pkg_path}"
spctl --assess -vv "${pkg_path}"
```

The code sign will end on:
```bash
>>> [sign] Signing the app
dist/test.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: ~/dist/test.app/Contents/MacOS/PyQt5/Qt/qml/QtQml/Models.2

>>> [sign] Verifying code signature
dist/test.app: code object is not signed at all
In architecture: x86_64
dist/test.app: rejected
source=no usable signature
```

---

This issue seems to be that `codesign` dislikes folders like `Models.2` (ending with a number perhaps?). I did not find a fix for now. Renaming the folder breaks everything.

Stack:
- Python 3.6.6
- PyQt5 5.11.2
- PyInstaller : 3.3.1 and `develop` branch
- macOS (any version >= 10.10, same results)

Let me know if you have clues , I can test everything :)
