### ISSUE TITLE
no freebsd bootloader in v4.0 release?

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#5224]
## Description of the issue

When using the v4.0 release tag code checkout from github and trying to build an executable on freebsd 12.1, I get:

```
    freebsd64: 24950 INFO: Bootloader /vagrant/.pyenv/versions/3.6.10/envs/borg-env/lib/python3.6/site-packages/pyinstaller-4.0+g19fb799a-py3.6.egg/PyInstaller/bootloader/FreeBSD-64bit/run
    freebsd64: 24950 INFO: checking EXE
    freebsd64: 24950 INFO: Building EXE because EXE-00.toc is non existent
    freebsd64: 24950 INFO: Building EXE from EXE-00.toc
    freebsd64: 
    freebsd64: Fatal error: PyInstaller does not include a pre-compiled bootloader for your
    freebsd64: platform. For more details and instructions how to build the bootloader see
    freebsd64: <https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>
```

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0+g19fb799a```
* Version of Python: e.g. 3.6.10
* Platform: FreeBSD 12.1
* Did you also try this on another platform? Does it work there? Yes, it works on Linux.

Aren't releases supposed to contain the bootloaders for the supported platforms?
