### ISSUE TITLE
Feature: An official GitHub Action to build PyInstaller executables

### ISSUE THREAD

**Issue by cclauss** [pyinstaller/pyinstaller#6296]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Travis CI stops running and I need to move all my work over to GitHub Actions.

**Describe the solution you'd like**
What would be really cool would be if the pyinstaller project had a default GitHub Action like:
* https://github.com/codespell-project/actions-codespell
* https://black.readthedocs.io/en/stable/integrations/github_actions.html
* https://github.com/marketplace/actions/pyinstaller-windows
* https://github.com/topics/wine-pyinstaller

I know that making a one-size-fits-all GitHub Action for pyinstaller would be hard work but ___a sample GHA that could build Linux, macOS, and Windows executables___ and is supported by this community would be a powerful jumpstart for many.

**Describe alternatives you've considered**
URLs above, starting from scratch, going snowboarding.

**Additional context**

**Comment by Legorooj** [comment]
Making a GitHub action shouldn't actually be too hard. It's definitely something to consider.

**Comment by bwoodsend** [comment]
What would it do though that isn't just bogstandard Github Actions? The following would be a generic workflow to run PyInstaller. I guess the steps could be coalesced into a single action but I don't really see the point as all but the first of those steps require some form of user configuration which we'd have to forward and the first and last steps require authentication so will need to juggle access tokens too. I can see this being very useful as an example but not as a self contained action.
```yaml
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest, 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller your-code.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
```
