### ISSUE TITLE
Failed to get address for PyRun_SimpleString GetProcAddress: The specified procedure could not be found. [process exited with code 4294967295]

### ISSUE THREAD

**Issue by marios-pz** [pyinstaller/pyinstaller#6332]
Python Ver: 3.10
Pyinstaller and PIP: Up-to-date

I have made a spec file that turns my python project into a single exe with no sub folders, it works great and all
But when I compile the same process over GitHub Actions and then pull my repo to get my executables and open them 
I get this error.
```
Failed to get address for PyRun_SimpleString
GetProcAddress: The specified procedure could not be found.

[process exited with code 4294967295]
```
is it because I use a alpha version of python 3.10 in yaml? 

```
uses: actions/setup-python@v2
        with:
          persist-credentials: false 
          python-version: '3.10.0-alpha.1'
```
