### ISSUE TITLE
Can't add binary/data files using wildcard glob when using poethepoet

### ISSUE THREAD

**Issue by Interpause** [pyinstaller/pyinstaller#6751]
When using `poethepoet` to run tasks, glob paths have to be quoted else it will perform path expansion. For example:

```toml
[tool.poe.tasks]
works = "somecommand --path 'somedir\\*.txt'"
broken = "somecommand --path somedir\\*.txt"
```

However, this causes me to run into issue #2470, where the way PyInstaller splits up the `SRC;DEST` path causes it not to work. For example:

```sh
Unable to find "\package\'somedir\*.txt" when adding binary and data files.
```

One way to solve this would be to submit a Feature Request to `poethepoet` to have a flag to disable path expansion. However, that likely will not happen soon. I believe it makes more sense that PyInstaller should properly parse `SRC;DEST` for quotations when using `--add-binary`, `--add-data`, etc.

**Comment by Interpause** [comment]
Somehow, specifying the argument using the equal sign, like `--add-data='somedir\*.txt'`, instead of `--add-data 'somedir\*.txt'`, fixes the problem. Will close the issue but hopefully it can be added to the FAQ.

**Comment by Interpause** [comment]
On further observation of what exactly `poethepoet` was doing, the above fix does not work as using the equal sign actually causes `poethepoet` to perform path expansion again for some reason.

**Comment by bwoodsend** [comment]
Surely it makes far more sense for `poethepoet` to provide a complete syntax for passing special characters in arguments than for PyInstaller to inject special logic to guess what looks like a botched shell command and normalise it?

**Comment by bwoodsend** [comment]
Just glancing at [poethepoet's readme](https://github.com/nat-n/poethepoet#define-tasks-in-your-pyprojecttoml) I see that you can get shell-like quoting support simply by adding a `{shell = command}` wrapper.

```toml
[tool.poe.tasks]
works = { shell = 'pyinstaller --add-data "somedir/*.txt;." test.py' }
```
