### ISSUE TITLE
PyInstaller, issue to build a package with CUDA, CuDNN and Tensorflow on Windows 10

### ISSUE THREAD

**Issue by cberri** [pyinstaller/pyinstaller#7175]
Hi there,

First, thank you for developing and maintaining such a great tool. I am very new to pyinstaller and I apologies if I miss anything that might be obvious to you.

I am currently using pyinstaller to build a GUI to run a Deep Learning tool that uses CUDA, CuDNN and tensorflow. I am having my virtual environment in conda with the following dependency on Windows 10:

```yaml
1121 INFO: PyInstaller: 5.1
1122 INFO: Python: 3.8.13 (conda)
1129 INFO: Platform: Windows-10-10.0.19044-SP0

# To manually install the yml run: conda env create -f environment.yml
name: StarDistGUI
channels:
    - conda-forge
dependencies:
    - pip
    - python=3.8
    - cudatoolkit=11.3.1
    - cudnn=8.2
    - tensorflow=2.9.1=gpu_py38h4a6fda8_0
    - pyqt=5.15.7
    - pyqtwebengine=5.15.7
    - psutil
    - csvkit
    - setuptools
    - pyinstaller
    - hdf5
    - pip:
        - csbdeep==0.7.2
        - gputools==0.2.13
        - stardist==0.8.3
        - pyradiomics
        - connected-components-3d
        - ray
        - rais
```

I packaged my app with pyinstaller as below from PyCharm:

`pyinstaller --add-data="temp;./temp" --icon=stardist.ico stardistGUI.py  --hidden-import=skimage.filters.edges --collect-all tensorflow --noconfirm --clean`

`temp` contains my .ui file

Everything seems to work and I get the *build* and *dist* directories. I can start my tool from the *dist* directory without any problem.

Here comes the issue:

I have locally installed on my Windows 10 machine CUDA 11.0 with CuDNN 8.1.x and CUDA 11.3 with CuDNN 8.2.x. It should not matter because I provide CUDA and CuDNN for the tool in the conda environment:

```
- cudatoolkit=11.3.1
- cudnn=8.2
```

I build the tool with pyinstaller and things get strange. If I have set my windows 10 env variables for CUDA V11.0 with CuDNN 8.1.x the build tool pops the following error message:

```
2022-10-19 16:23:52.416036: E tensorflow/stream_executor/cuda/cuda_dnn.cc:377] Loaded runtime CuDNN library: 8.1.0 but source was compiled with: 8.2.1.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-10-19 16:23:52.425421: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
```

I printed the following after building the package with pyinstaller: GPU is recognized, CUDA seems all right (64_113), CuDNN I am honestly not sure (64_8). In conda I have CuDNN 8.2.x but locally 8.1.x.

```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

2022-10-19 16:08:35.405699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /device:GPU:0 with 7437 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:68:00.0, compute capability: 8.6
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16001663011293130701
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 7799234560
locality {
  bus_id: 1
  links {
  }
}
incarnation: 4786325627852168319
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:68:00.0, compute capability: 8.6"
xla_global_id: 416903419
]

import tensorflow as tf
build = tf.sysconfig.get_build_info()
print(build['cuda_version'])
print(build['cudnn_version'])

64_113
64_8
```

If I change my local env to CUDA 11.3 (set Windows 10 env variables to V11.3) everything works fine after building the app with pyinstaller. No error message it runs properly with the right version of CuDNN (8.2.x).

I think I am missing something or at least pyinstaller builds my package with the wrong CuDNN libraries or somehow looks only at my local installation and not what is in my conda environment. From PyCharm I can run successfully the tool independently from what I have in my local environment. After a week I have no more ideas how to solve the issue and I would really appreciate your suggestions.

If I miss any meaningful information for you please let me know and also if something is not clear in my question. I tried my best to explain the problem but it is not really straightforward.

Thank you in advance for your help.

Best regards,

Carlo
