### ISSUE TITLE
building bootloader fails with Developer Command Prompt for Microsoft Visual C++

### ISSUE THREAD

**Issue by sabonerune** [pyinstaller/pyinstaller#7558]
## Description of the issue

building bootloader fails with Developer Command Prompt or PowerShell.

<details>
<summary>Workflow created for reproduction</summary>

```yaml
name: Build Bootloader Test
on: push

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
        os: ['windows-2019', 'windows-2022']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set cache dir
        run: echo "pip_cache_dir=$(pip cache dir)" >> $GITHUB_ENV
        shell: bash

      - name: Fetch cache
        id: cache-target
        uses: actions/cache@v3
        with:
          path: ${{ env.pip_cache_dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build bootloader
        run: |
          cd bootloader
          python waf all
```
</details>

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.8.10```
* Version of Python: `3.7`, `3.8`, `3.9`, `3.10`, `3.11`
* Platform: `Windows`
* How you installed Python: `python.org/downloads`
* Did you also try this on another platform? Does it work there? 

I have Windows only. But I don't think it happens on other OS from the Github results.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```cmd
rem In X64 native Developer Command Prompt for VS2019
cd bootloader
python waf all
```

### Stacktrace / full error message

```
invalid lock file in D:\Dev\pyinstaller\bootloader
'all' finished successfully (0.001s)
'distclean' finished successfully (0.022s)
Setting top to                           : D:\Dev\pyinstaller\bootloader
Setting out to                           : D:\Dev\pyinstaller\bootloader\build
Python Version                           : 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe
Checking size of pointer                 : 8
Platform                                 : Windows-64bit-arm detected based on compiler
Build tests                              : disabled
Checking for function unsetenv           : no
Checking for function mkdtemp            : no
Checking for function dirname            : no
Checking for function basename           : no
Checking for function strndup            : no
Checking for function strnlen            : no
'configure' finished successfully (2.049s)
'make_all' finished successfully (0.011s)
Waf: Entering directory `D:\Dev\pyinstaller\bootloader\build\debug'
[ 1/21] Compiling zlib\zutil.c
[ 2/21] Compiling zlib\inffast.c
[ 3/21] Compiling zlib\adler32.c
[ 4/21] Compiling zlib\inftrees.c
zutil.c
[ 5/21] Compiling zlib\crc32.c
inffast.c
inftrees.c
[ 6/21] Compiling zlib\inflate.c
[ 7/21] Compiling src\pyi_apple_events.c
adler32.c
[ 8/21] Compiling src\pyi_main.c
pyi_apple_events.c
[ 9/21] Compiling src\pyi_global.c
crc32.c
[10/21] Compiling src\pyi_path.c
inflate.c
[11/21] Compiling src\pyi_win32_utils.c
pyi_global.c
[12/21] Compiling src\pyi_utils.c
pyi_main.c
[13/21] Compiling src\pyi_launch.c
pyi_path.c
[14/21] Compiling src\pyi_splashlib.c
pyi_win32_utils.c
[15/21] Compiling src\pyi_archive.c
pyi_utils.c
[16/21] Compiling src\pyi_splash.c
pyi_splashlib.c
[17/21] Compiling src\pyi_pythonlib.c
pyi_launch.c
[18/21] Compiling src\pyi_python.c
pyi_archive.c
[19/21] Compiling src\pyi_exception_dialog.c
pyi_exception_dialog.c
[20/21] Compiling src\main.c
pyi_splash.c
pyi_python.c
pyi_pythonlib.c
main.c
[21/21] Linking build\debug\run_d.exe
LINK : warning LNK4010: invalid subsystem version number 5.02; default subsystem version assumed
src\main.c.3.o : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'
Waf: Leaving directory `D:\Dev\pyinstaller\bootloader\build\debug'
Build failed
 -> task in 'run_d' failed with exit status 1112 (run with -v to display more information)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.
