### ISSUE TITLE
Stuck at "Looking for dynamic library"

### ISSUE THREAD

**Issue by matinmoezzi** [pyinstaller/pyinstaller#8396]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```PyInstaller: 6.5.0, contrib hooks: 2024.3```
* Version of Python: 3.8.10
* Platform: Windows-10-10.0.20348-SP0 (GitHub Action `windows-latest` runner)
* How you installed Python: `pip` via GitHub Action `actions/setup-python@v5`
* Did you also try this on another platform? Does it work there?
It works locally on `Mac`, `Linux`, and `Win11` and also it works on GitHub Action `Mac` and `Linux` runner. However, it stucks on `windows-lates` in GitHub Action Runner.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Tried but it didn't work.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
build:
    name: Build packages
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest 
            TARGET: windows
            CMD_BUILD: >
              pyinstaller --debug=all --noupx main.py 
              --hiddenimport module1 --hiddenimport module2
              --collect-data module3 --add-data ./config:./config &&
              cd dist/ &&
              Compress-Archive app app_win.zip
            OUT_FILE_NAME: app_win.zip
            ASSET_MIME: application/zip

    steps:
    - uses: actions/checkout@v4
      with:
        ref: "feature/gh-action"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -e .
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
```

### Stacktrace / full error message

```
...
23981 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks'...
23981 INFO: checking Tree
23981 INFO: Building Tree because Tree-00.toc is non existent
23981 INFO: Building Tree Tree-00.toc
25487 INFO: checking Tree
25487 INFO: Building Tree because Tree-01.toc is non existent
25487 INFO: Building Tree Tree-01.toc
25612 INFO: checking Tree
25612 INFO: Building Tree because Tree-02.toc is non existent
25612 INFO: Building Tree Tree-02.toc
25643 INFO: Performing binary vs. data reclassification (2366 entries)
29756 INFO: Looking for ctypes DLLs
29850 INFO: Analyzing run-time hooks ...
29866 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
29866 INFO: Processing pre-find module path hook _pyi_rth_utils from 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
29866 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks'...
29866 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_traitlets.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
29881 INFO: Including run-time hook 'c:\\hostedtoolcache\\windows\\python\\3.8.10\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pyqtgraph_multiprocess.py'
31[132]INFO: Looking for dynamic libraries
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.
