### ISSUE TITLE
Qt applications not running on Linux because of missing plugins xcb and wayland

### ISSUE THREAD

**Issue by RumovZ** [pyinstaller/pyinstaller#8658]
## Description of the issue

Qt applications don't run on Linux, apparently because the plugins xcb and wayland are not packaged correctly.

This used to work and broke somewhere between 6.3 and 6.7.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.9.0```
* Version of Python: 3.11.9
* Platform: Ubuntu 22.04
* How you installed Python: https://github.com/actions/setup-python
* Did you also try this on another platform? Does it work there? Also doesn't work on WSL.

(I did the things.)

### A minimal example program which shows the error

```python
import sys
from PySide6 import QtWidgets

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mw = QtWidgets.QMainWindow()
    mw.show()
    app.exec()
```

I'm using a GitHub workflow and act to build this locally in a container:

```yaml
name: Release

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.6.*"
          setup-python: false
          dir: "."
      - name: Install dependencies
        run: |
          python -m pip install "PySide6==6.6.*"
          python -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
          python -m pip install pyinstaller-hooks-contrib
          python -m pip freeze
          pyinstaller --version
      - name: Build with pyinstaller
        run: pyinstaller -n 'my_app' __init__.py --noupx --debug all --onedir
```

### Stacktrace / full error message

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.    

Aborted
```
I can provide the build and debug logs as well if required.

<hr>
Possibly reported before in #8541.
